### ISSUE TITLE
Support n-sfw.com

### ISSUE THREAD

**Issue by MaximilianGT500** [cranci1/AnimeGen#2]
Hey,

I would really like it if you would also support https://n-sfw.com. The API is the same as https://waifu.pics.

**Website**: https://n-sfw.com/
**API-Docs**: [https://n-sfw.com/docs](https://n-sfw.com/docs)
**SFW category**: bunny-girl, charlotte, date-a-live, death-note, demon-slayer, haikyu, hxh, kakegurui, konosuba, komi, memes, naruto, noragami, one-piece, rag, sakurasou, sao, sds, spy-x-family, takagi-san, toradora, your-name
**NSFW category**: anal, ass, blowjob, breeding, buttplug, cages, ecchi, feet, fo, furry, gif, hentai, legs, masturbation, milf, muscle, neko, paizuri, petgirls, pierced, selfie, smothering, socks, trap, vagina, yaoi, yuri

Yours sincerely,
Max

**Comment by cranci1** [comment]
Hey,

Thanks for the suggestion! 
The n-sfw api will be added in around 10h since i have 7 hours of school (i has sleeping before), but once i finished school i'll add the api to the app.

Thanks,
cranci

**Comment by cranci1** [comment]
Hello,

I wanted to ask you if you would like to be added on the "Contribution Credits" page in the settings?
Is ok this?
![Screenshot 2024-05-15 at 15 10 08](https://github.com/cranci1/AnimeGen/assets/100066266/c3359e05-30f8-4858-94f8-aff713944ea4)
(when clicking your name the user will be taken to your github account page)

**Comment by cranci1** [comment]
Hey,

Thanks for the suggestion!
The api has been successfully added!

Thanks,
cranci

**Comment by MaximilianGT500** [comment]
Hey,

thank you. Yes you can add me in the "Contribution Credits" section in the settings.

Also an "bug" in the settings you can't select the n-sfw api. Also I think it looks better when you name it: "n-sfw.com".

Thanks,
Max

**Comment by MaximilianGT500** [comment]
Hey,

when you click on the safari icon it only shows an picture of waifu.im. 

Thanks,
Max

**Comment by cranci1** [comment]
Hey,

Ok I should have fixed everything! 
Once the build is accepted on testflight let me know if everything is fixed!

Thank you so much!
cranci

**Comment by cranci1** [comment]
Ok wait im dumb i forgot a little thing now once is accepted everything should work.
(For real this time)

Edit:
Is now working correctly on my device. Tell me if it works on your device.
